spring:
  datasource:
    url: jdbc:h2:mem:libraryDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password

library:
  maxBooksByUser: 5
  maxLoanDurationInDays: 14

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
